# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wkt_geometry', models.TextField(blank=True)),
                ('csw_typename', models.CharField(default='csw:Record', max_length=200)),
                ('csw_schema', models.CharField(default='http://www.opengis.net/cat/csw/2.0.2', max_length=200)),
                ('csw_mdsource', models.CharField(default='local', max_length=100)),
                ('csw_xml', models.TextField(blank=True)),
                ('csw_anytext', models.TextField(blank=True)),
            ],
        ),
    ]
